import type { NextPage } from 'next';
import { signIn } from 'next-auth/react';
import Head from 'next/head';
import { matchRoles } from 'utils/matchRoles';

export async function getServerSideProps(context) {
  return {
    props: { ...(await matchRoles(context)) },
  };
}

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Join us</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <button
      type='button'
      onClick={() => {
        signIn('auth0');
      }}
    >
      Iniciar sesión
    </button>
  </div>
);

export default Home;
